In [5]:


!pip install nest_asyncio



In [6]:

import nest_asyncio
nest_asyncio.apply()

In [7]:

# AAS project will go here
import sys
import datetime
from netaddr import IPNetwork, IPAddress, IPSet
import pyshark

In [9]:
async def pktHandler(timestamp,srcIP,dstIP,lengthIP,sampDelta,outfile):
    global scnets
    global ssnets
    global npkts
    global T0
    global outc
    global last_ks
    
    if (IPAddress(srcIP) in scnets and IPAddress(dstIP) in ssnets) or (IPAddress(srcIP) in ssnets and IPAddress(dstIP) in scnets):
        if npkts==0:
            T0=float(timestamp)
            last_ks=0
            
        ks=int((float(timestamp)-T0)/sampDelta)
        
        if ks>last_ks:
            outfile.write('{} {} {} {} {}\n'.format(last_ks,*outc))
            print('{} {} {} {} {}'.format(last_ks,*outc))
            outc=[0,0,0,0]  
            
        if ks>last_ks+1:
            for j in range(last_ks+1,ks):
                outfile.write('{} {} {} {} {}\n'.format(j,*outc))
                print('{} {} {} {} {}'.format(j,*outc))
                  
        
        if IPAddress(srcIP) in scnets: #Upload
            outc[0]=outc[0]+1
            outc[1]=outc[1]+int(lengthIP)

        if IPAddress(dstIP) in scnets: #Download
            outc[2]=outc[2]+1
            outc[3]=outc[3]+int(lengthIP)
        
        last_ks=ks
        npkts=npkts+1

In [11]:
# code from basePktSampling
# Pcket sampling

# ------Variables go here-------
CNETS="172.16.183.0/24" # client (src)
sampDelta=1
SNETS="0.0.0.0/0" # service (dest)
fileOutput="1_sampled_data.dat"
fileInput="cleanest_dset.pcapng"
#--------------------------------


cnets=[]
nn=IPNetwork(CNETS)
cnets.append(nn)

global scnets
scnets=IPSet(cnets)

snets=[]
nn=IPNetwork(SNETS)
snets.append(nn)

global ssnets
ssnets=IPSet(snets)

global npkts
global T0
global outc
global last_ks

npkts=0
outc=[0,0,0,0]

outfile = open(fileOutput,'w') 

capture = pyshark.FileCapture(fileInput,display_filter='ip')
for pkt in capture:
    timestamp,srcIP,dstIP,lengthIP=pkt.sniff_timestamp,pkt.ip.src,pkt.ip.dst,pkt.ip.len
    await pktHandler(timestamp,srcIP,dstIP,lengthIP,sampDelta,outfile)

outfile.close()

0 17 1589 18 17215
1 45 5987 45 27535
2 10 680 10 1173
3 0 0 0 0
4 3 275 3 3297
5 0 0 0 0
6 14 803 14 37454
7 0 0 0 0
8 8 476 8 476
9 18 6664 19 5405
10 36 8231 39 9628
11 2 80 2 80
12 16 2790 16 1891
13 138 8382 139 863539
14 50 12610 54 23284
15 91 11975 97 411628
16 10 1805 10 1406
17 0 0 0 0
18 0 0 0 0
19 6 2821 7 491
20 0 0 0 0
21 4 199 4 199
22 0 0 0 0
23 0 0 0 0
24 9 1906 9 764
25 8 398 8 398
26 14 1845 13 4950
27 16 929 16 851
28 0 0 0 0
29 279 22700 305 1187417
30 191 29768 210 173935
31 249 32368 273 233019
32 260 25663 309 625177
33 235 28559 274 272975
34 195 22328 227 249120
35 214 27027 254 272893
36 205 23732 227 261239
37 193 21259 238 248658
38 193 23207 225 245334
39 206 23770 233 266247
40 215 25492 250 265522
41 217 24202 239 257502
42 215 24173 251 276379
43 114 12909 133 137329
44 132 14525 152 187257
45 2 2561 3 237
46 2 119 2 119
47 0 0 0 0
48 0 0 0 0
49 2 119 2 119
50 2 119 2 119
51 1 40 1 40
52 7 319 7 319
53 0 0 0 0
54 0 0 0 0
55 2 119 2 119
56 2 119 2 119
57

538 111 10534 118 522963
539 29 3686 33 17054
540 80 7492 95 299291
541 153 7882 173 3232634
542 2 196 2 5865
543 9 1318 11 3959
544 36 2764 52 57876
545 4 1033 7 1289
546 3 960 5 345
547 71 4746 94 155674
548 49 3708 53 663300
549 82 4303 101 1664108
550 9 1077 9 5250
551 10 400 10 19596
552 159 24046 161 73070
553 200 30832 239 162487
554 44 7252 46 33277
555 55 3494 67 492936
556 20 1711 21 166258
557 0 0 0 0
558 6 693 6 360
559 36 5137 36 17570
560 42 5430 45 25597
561 41 3148 53 83156
562 1 40 0 0
563 20 1808 19 22092
564 8 320 8 12511
565 1 249 1 40
566 115 7188 135 794194
567 93 5214 102 1279517
568 7 1261 7 3507
569 56 8388 54 40790
570 0 0 0 0
571 69 10541 67 23394
572 198 25366 354 388294
573 72 14475 110 88332
574 82 9533 86 143463
575 225 17046 253 1360160
576 14 1064 15 46451
577 0 0 0 0
578 0 0 0 0
579 4 238 4 238
580 15 857 15 818
581 0 0 0 0
582 0 0 0 0
583 3 187 4 223
584 2 80 2 80
585 0 0 0 0
586 0 0 0 0
587 0 0 0 0
588 2 126 2 126
589 0 0 0 0
590 6 772 6 400
591 0 0 

1076 30 4483 29 13150
1077 0 0 0 0
1078 1 40 1 161
1079 9 930 9 477
1080 0 0 0 0
1081 4 238 4 238
1082 0 0 0 0
1083 1 40 1 40
1084 2 126 2 126
1085 4 238 4 238
1086 0 0 0 0
1087 4 238 4 238
1088 0 0 0 0
1089 0 0 0 0
1090 2 126 2 126
1091 5 306 6 342
1092 0 0 0 0
1093 9 516 8 476
1094 6 296 7 376
1095 0 0 0 0
1096 0 0 0 0
1097 0 0 1 40
1098 0 0 0 0
1099 18 1370 18 1370
1100 0 0 0 0
1101 0 0 0 0
1102 0 0 0 0
1103 0 0 0 0
1104 1 40 1 40
1105 12 721 12 721
1106 0 0 2 80
1107 0 0 10 400
1108 0 0 3 120
1109 1 40 1 161
1110 3 610 6 240
1111 10 595 10 595
1112 4 653 4 281
1113 0 0 0 0
1114 1 40 6 240
1115 0 0 0 0
1116 0 0 0 0
1117 10 602 10 602
1118 0 0 0 0
1119 0 0 0 0
1120 0 0 0 0
1121 0 0 0 0
1122 1 68 5 224
1123 11 670 12 706
1124 1 40 1 40
1125 1 169 0 0
1126 4 223 4 160
1127 0 0 0 0
1128 0 0 0 0
1129 10 602 10 602
1130 0 0 0 0
1131 2 119 2 119
1132 6 342 6 279
1133 3 183 4 223
1134 1 40 1 40
1135 10 602 10 602
1136 10 2344 15 6442
1137 23 3688 63 72742
1138 0 0 3 120
1139 0 0 0 0
1140 8 

1756 21 4545 25 5660
1757 21 1754 20 3578
1758 27 4068 26 12065
1759 28 2660 21 2930
1760 18 1825 15 1868
1761 28 3861 24 4607
1762 167 30336 263 202322
1763 110 18512 359 405456
1764 0 0 0 0
1765 0 0 0 0
1766 5 1315 5 341
1767 11 685 71 84132
1768 11 2719 17 7713
1769 12 3342 14 2754
1770 18 3927 38 26529
1771 54 9191 363 470339
1772 201 35476 591 699072
1773 0 0 0 0
1774 0 0 0 0
1775 0 0 0 0
1776 0 0 0 0
1777 0 0 0 0
1778 0 0 0 0
1779 0 0 0 0
1780 5 439 5 439
1781 0 0 0 0
1782 0 0 0 0
1783 5 718 6 385
1784 0 0 0 0
1785 4 653 4 281
1786 0 0 0 0
1787 0 0 0 0
1788 1 68 2 104
1789 0 0 0 0
1790 0 0 0 0
1791 0 0 0 0
1792 0 0 0 0
1793 0 0 0 0
1794 12 1367 11 1427
1795 0 0 0 0
1796 0 0 0 0
1797 0 0 0 0
1798 0 0 0 0
1799 0 0 0 0
1800 0 0 0 0
1801 17 2654 17 6807
1802 0 0 0 0
1803 0 0 0 0
1804 0 0 0 0
1805 0 0 0 0
1806 0 0 0 0
1807 0 0 0 0
1808 0 0 0 0
1809 0 0 0 0
1810 0 0 0 0
1811 0 0 0 0
1812 1 76 1 76
1813 2 136 4 208
1814 0 0 0 0
1815 0 0 0 0
1816 0 0 0 0
1817 0 0 0 0
1818 0 0 0 0
1819 0 

2335 8 446 9 432
2336 3 148 2 201
2337 3 573 3 120
2338 0 0 0 0
2339 0 0 0 0
2340 0 0 0 0
2341 0 0 0 0
2342 0 0 0 0
2343 0 0 0 0
2344 0 0 0 0
2345 0 0 0 0
2346 0 0 0 0
2347 0 0 0 0
2348 4 650 4 281
2349 4 223 4 160
2350 4 223 4 160
2351 0 0 0 0
2352 0 0 0 0
2353 2 108 3 265
2354 3 613 3 120
2355 0 0 0 0
2356 0 0 0 0
2357 0 0 0 0
2358 0 0 0 0
2359 0 0 0 0
2360 2 108 2 104
2361 0 0 0 0
2362 0 0 0 0
2363 0 0 0 0
2364 0 0 0 0
2365 0 0 0 0
2366 2 119 2 119
2367 0 0 0 0
2368 0 0 0 0
2369 0 0 0 0
2370 0 0 0 0
2371 4 223 4 160
2372 0 0 0 0
2373 0 0 0 0
2374 0 0 0 0
2375 0 0 0 0
2376 0 0 0 0
2377 0 0 0 0
2378 0 0 0 0
2379 0 0 0 0
2380 0 0 0 0
2381 0 0 0 0
2382 0 0 0 0
2383 1 68 2 104
2384 0 0 0 0
2385 0 0 0 0
2386 0 0 0 0
2387 0 0 0 0
2388 0 0 0 0
2389 0 0 0 0
2390 0 0 0 0
2391 0 0 0 0
2392 1 68 2 104
2393 0 0 0 0
2394 10 722 9 782
2395 0 0 0 0
2396 0 0 0 0
2397 0 0 0 0
2398 0 0 0 0
2399 0 0 0 0
2400 1 40 1 160
2401 3 613 3 120
2402 0 0 0 0
2403 0 0 0 0
2404 0 0 0 0
2405 3 120 3 483
2406 3 573 

2887 2 126 2 126
2888 6 357 6 357
2889 0 0 0 0
2890 0 0 0 0
2891 4 261 5 14235
2892 0 0 0 0
2893 207 17299 235 1329038
2894 10 580 10 517
2895 0 0 0 0
2896 0 0 0 0
2897 4 223 4 160
2898 0 0 0 0
2899 2 126 2 126
2900 4 238 4 238
2901 1 68 2 104
2902 0 0 0 0
2903 0 0 0 0
2904 0 0 0 0
2905 11 1057 11 905
2906 9 930 9 477
2907 0 0 0 0
2908 0 0 0 0
2909 0 0 0 0
2910 0 0 0 0
2911 2 126 2 126
2912 4 238 4 238
2913 0 0 0 0
2914 0 0 0 0
2915 0 0 0 0
2916 0 0 0 0
2917 8 619 8 619
2918 4 238 4 238
2919 0 0 0 0
2920 4 223 4 160
2921 4 650 4 281
2922 0 0 0 0
2923 1 68 2 104
2924 8 461 8 422
2925 0 0 0 0
2926 0 0 0 0
2927 2 126 2 126
2928 0 0 0 0
2929 0 0 0 0
2930 4 238 4 238
2931 0 0 0 0
2932 0 0 0 0
2933 2 126 2 126
2934 4 223 4 160
2935 0 0 0 0
2936 4 238 4 238
2937 0 0 0 0
2938 1 68 2 104
2939 2 126 2 126
2940 0 0 0 0
2941 0 0 0 0
2942 4 238 4 238
2943 0 0 0 0
2944 0 0 0 0
2945 3 166 3 287
2946 3 613 3 120
2947 0 0 0 0
2948 4 238 4 238
2949 0 0 0 0
2950 0 0 0 0
2951 4 245 4 245
2952 0 0 0 0
2953

3419 38 9962 43 46431
3420 23 1695 23 1778
3421 32 1386 34 406057
3422 0 0 0 0
3423 0 0 0 0
3424 10 2699 10 1572
3425 2 126 2 126
3426 12 675 12 675
3427 2 119 2 119
3428 0 0 0 0
3429 0 0 0 0
3430 7 1721 7 445
3431 2 126 2 126
3432 10 595 10 595
3433 2 119 2 119
3434 4 188 5 296
3435 11 1063 10 1003
3436 13 1849 14 6095
3437 10 595 10 595
3438 2 119 2 119
3439 0 0 0 0
3440 1 40 1 162
3441 5 732 5 239
3442 2 119 2 119
3443 10 595 10 595
3444 6 493 6 493
3445 0 0 0 0
3446 4 206 4 206
3447 2 119 2 119
3448 6 342 6 303
3449 8 476 8 476
3450 2 119 2 119
3451 0 0 0 0
3452 2 126 2 126
3453 0 0 0 0
3454 0 0 0 0
3455 0 0 0 0
3456 12 675 12 675
3457 4 238 4 238
3458 2 126 2 126
3459 0 0 0 0
3460 0 0 0 0
3461 0 0 0 0
3462 10 595 10 595
3463 6 346 6 342
3464 2 126 2 126
3465 1 40 1 162
3466 14 3000 15 3127
3467 0 0 0 0
3468 10 595 10 595
3469 10 1147 11 566
3470 5 200 5 21817
3471 5 970 8 5760
3472 8 401 24 65187
3473 41 3503 42 366688
3474 22 4666 42 35446
3475 32 6529 32 4564
3476 2 80 2 80
3477

3957 4 245 4 245
3958 2 119 2 119
3959 0 0 0 0
3960 6 325 6 325
3961 0 0 0 0
3962 0 0 0 0
3963 4 245 4 245
3964 25 3034 26 14763
3965 33 1320 49 121771
3966 4 245 4 245
3967 0 0 0 0
3968 0 0 0 0
3969 4 245 4 245
3970 4 199 4 199
3971 0 0 0 0
3972 4 245 4 245
3973 1 68 2 104
3974 0 0 0 0
3975 0 0 0 0
3976 0 0 0 0
3977 0 0 0 0
3978 0 0 0 0
3979 10 609 10 609
3980 0 0 0 0
3981 2 80 2 80
3982 0 0 0 0
3983 15 764 20 86709
3984 19 1575 22 65215
3985 15 1031 15 15980
3986 159 9615 180 2147366
3987 104 4195 124 3862505
3988 9 651 9 651
3989 7 768 6 708
3990 14 2318 14 5677
3991 12 664 12 660
3992 0 0 0 0
3993 0 0 0 0
3994 0 0 0 0
3995 2 126 2 126
3996 0 0 0 0
3997 6 357 6 357
3998 0 0 0 0
3999 0 0 0 0
4000 2 80 0 0
4001 6 286 6 286
4002 0 0 0 0
4003 7 425 8 461
4004 2 115 2 111
4005 0 0 0 0
4006 0 0 0 0
4007 2 126 2 126
4008 0 0 0 0
4009 6 357 6 357
4010 0 0 0 0
4011 61 3904 67 861577
4012 0 0 0 0
4013 0 0 0 0
4014 2 80 3 192
4015 0 0 0 0
4016 0 0 0 0
4017 0 0 0 0
4018 9 551 9 523
4019 0 0 0 0

4501 15 3006 14 5521
4502 8 804 9 1947
4503 0 0 0 0
4504 0 0 0 0
4505 0 0 0 0
4506 0 0 0 0
4507 0 0 0 0
4508 2 126 2 126
4509 0 0 0 0
4510 0 0 0 0
4511 0 0 0 0
4512 0 0 0 0
4513 1 68 2 104
4514 2 126 2 126
4515 0 0 0 0
4516 0 0 0 0
4517 0 0 0 0
4518 2 108 2 104
4519 0 0 0 0
4520 2 126 2 126
4521 0 0 0 0
4522 0 0 0 0
4523 0 0 0 0
4524 0 0 0 0
4525 0 0 0 0
4526 12 848 11 908
4527 0 0 0 0
4528 0 0 0 0
4529 4 653 4 281
4530 0 0 0 0
4531 0 0 0 0
4532 1 40 1 162
4533 3 610 3 120
4534 0 0 0 0
4535 0 0 0 0
4536 0 0 0 0
4537 7 3662 8 2721
4538 2 126 2 126
4539 0 0 0 0
4540 0 0 0 0
4541 0 0 0 0
4542 0 0 0 0
4543 2 136 4 208
4544 25 6819 25 2820
4545 3 188 38 49477
4546 4 2459 4 242
4547 0 0 0 0
4548 0 0 0 0
4549 0 0 0 0
4550 54 9243 173 208576
4551 0 0 0 0
4552 22 2860 77 85960
4553 14 1784 73 90305
4554 7 1312 41 47725
4555 0 0 0 0
4556 7 4258 34 37810
4557 36 5059 129 151555
4558 42 5759 111 106193
4559 0 0 0 0
4560 34 4538 143 162763
4561 31 3667 87 92113
4562 3 224 2 164
4563 51 10317 124 12

5026 5 276 5 41363
5027 1 86 1 40
5028 11 635 11 681
5029 0 0 0 0
5030 0 0 0 0
5031 4 513 4 2448
5032 0 0 0 0
5033 1 86 1 40
5034 13 1029 14 3932
5035 0 0 0 0
5036 0 0 0 0
5037 3 198 3 159
5038 30 1277 31 186523
5039 4 160 5 9608
5040 11 1125 11 557
5041 2 80 2 158
5042 0 0 0 0
5043 4 223 4 184
5044 3 205 3 159
5045 1 40 1 86
5046 4 316 4 160
5047 5 510 5 356
5048 0 0 0 0
5049 87 3480 106 652419
5050 7 494 7 33762
5051 2 80 2 165
5052 6 424 6 264
5053 5 228 6 420
5054 0 0 0 0
5055 0 0 0 0
5056 0 0 0 0
5057 0 0 0 0
5058 0 0 0 0
5059 0 0 0 0
5060 15 841 16 1037
5060 1 40 1 86
5061 1 40 0 0
5062 0 0 0 0
5063 0 0 0 0
5064 0 0 0 0
5065 4 307 4 181
5066 35 6405 49 47726
5067 23 3456 32 22640
5068 43 6959 39 10407
5069 5 847 2 118
5070 29 4424 25 6231
5071 54 8076 51 14498
5072 45 8073 53 10021
5073 25 3666 29 16516


In [12]:
# analyze with sliding window

import numpy as np
import matplotlib.pyplot as plt
import os

In [13]:
def slidingObsWindow(data,lengthObsWindow,slidingValue,basename):
    iobs=0
    nSamples,nMetrics=data.shape
    obsData=np.zeros((0,lengthObsWindow,nMetrics))
    for s in np.arange(lengthObsWindow,nSamples,slidingValue):
        subdata=data[s-lengthObsWindow:s,:]
        obsData=np.insert(obsData,iobs,subdata,axis=0)

        obsFname="{}_obs{}_w{}.dat".format(basename,iobs,lengthObsWindow)
        iobs+=1
        np.savetxt(obsFname,subdata,fmt='%d')

    return obsData # 3D arrays (obs, sample, metric)

In [15]:
fileInput="1_sampled_data.dat"
lengthObsWindow=[15]
slidingValue=3

data=np.loadtxt(fileInput,dtype=int)
fname=''.join(fileInput.split('.')[:-1])

dirname=fname+"_obs_s{}_m{}".format(slidingValue,"2")

os.mkdir(dirname)
basename=dirname+"/"+fname

print("\n\n### SLIDING Observation Windows with Length {} and Sliding {} ###".format(lengthObsWindow[0],slidingValue))
obsData=slidingObsWindow(data,lengthObsWindow[0],slidingValue,basename)
print(obsData)



### SLIDING Observation Windows with Length 15 and Sliding 3 ###
[[[0.00000e+00 1.70000e+01 1.58900e+03 1.80000e+01 1.72150e+04]
  [1.00000e+00 4.50000e+01 5.98700e+03 4.50000e+01 2.75350e+04]
  [2.00000e+00 1.00000e+01 6.80000e+02 1.00000e+01 1.17300e+03]
  ...
  [1.20000e+01 1.60000e+01 2.79000e+03 1.60000e+01 1.89100e+03]
  [1.30000e+01 1.38000e+02 8.38200e+03 1.39000e+02 8.63539e+05]
  [1.40000e+01 5.00000e+01 1.26100e+04 5.40000e+01 2.32840e+04]]

 [[3.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
  [4.00000e+00 3.00000e+00 2.75000e+02 3.00000e+00 3.29700e+03]
  [5.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
  ...
  [1.50000e+01 9.10000e+01 1.19750e+04 9.70000e+01 4.11628e+05]
  [1.60000e+01 1.00000e+01 1.80500e+03 1.00000e+01 1.40600e+03]
  [1.70000e+01 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]]

 [[6.00000e+00 1.40000e+01 8.03000e+02 1.40000e+01 3.74540e+04]
  [7.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
  [8.00000e+00 8.0000

In [24]:
# Extract Features
import argparse
import scipy.stats as stats
import numpy as np
import matplotlib.pyplot as plt
from baseObsWindows import slidingMultObsWindow
import os

def extractFeatures(dirname,basename,nObs,allwidths):
    for o in range(0,nObs):
        features=np.array([])
        for oW in allwidths:
            obsfilename=dirname+"/"+basename+str(o)+"_w"+str(oW)+".dat"
            print(obsfilename)
            subdata=np.loadtxt(obsfilename)[:,1:]    #Loads data and removes first column (sample index)
                
            faux=extractStats(subdata)    
            features=np.hstack((features,faux))
            
            faux2=extractStatsSilenceActivity(subdata)
            features=np.hstack((features,faux2))
        if o==0:
            obsFeatures=features
        else:
            obsFeatures=np.vstack((obsFeatures,features))

    return obsFeatures


def extractStatsSilenceActivity(data):
    features=[]
    nSamples,nMetrics=data.shape
    silence_features=np.array([])
    activity_features=np.array([])
    for c in range(nMetrics):
        silence,activity=extratctSilenceActivity(data[:,c],threshold=0)
        
        if len(silence)>0:
            silence_faux=np.array([len(silence),np.mean(silence),np.std(silence)])
        else:
            silence_faux=np.zeros(3)
        silence_features=np.hstack((silence_features,silence_faux))
        
        if len(activity)>0:
            activity_faux=np.array([len(activity),np.mean(activity),np.std(activity)])
        else:
            activity_faux=np.zeros(3)
        activity_features=np.hstack((activity_features,activity_faux))       
            
    features=np.hstack((silence_features,activity_features))
        
    return(features)

def extratctSilenceActivity(data,threshold=0):
    if(data[0]<=threshold):
        s=[1]
        a=[]
    else:
        s=[]
        a=[1]
    for i in range(1,len(data)):
        if(data[i-1]>threshold and data[i]<=threshold):
            s.append(1)
        elif(data[i-1]<=threshold and data[i]>threshold):
            a.append(1)
        elif (data[i-1]<=threshold and data[i]<=threshold):
            s[-1]+=1
        else:
            a[-1]+=1
    return(s,a)

def extractStats(data):
    nSamp,nCols=data.shape

    M1=np.mean(data,axis=0)
    Md1=np.median(data,axis=0)
    Std1=np.std(data,axis=0)
    S1=stats.skew(data)
    #K1=stats.kurtosis(data)
    p=[75,90,95,98]
    Pr1=np.array(np.percentile(data,p,axis=0)).T.flatten()
        
    features=np.hstack((M1,Md1,Std1,S1,Pr1))
    return(features)


In [26]:

dirname="1_sampled_data_obs_s3_m2"
allwidths=[15]

allfiles=os.listdir(dirname)
nObs=len([f for f in allfiles if '_w{}.'.format(allwidths[0]) in f])
lbn=allfiles[0].rfind("obs")+3
basename=allfiles[0][:lbn]

features=extractFeatures(dirname,basename,nObs,allwidths)

outfilename=basename+"_features.dat"


np.savetxt(outfilename,features,fmt='%.4f')

print(features.shape)

1_sampled_data_obs_s3_m2/1_sampled_data_obs0_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs2_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs3_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs4_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs5_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs6_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs7_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs8_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs9_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs10_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs11_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs12_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs13_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs14_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs15_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs16_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs17_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_dat

1_sampled_data_obs_s3_m2/1_sampled_data_obs234_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs235_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs236_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs237_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs238_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs239_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs240_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs241_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs242_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs243_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs244_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs245_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs246_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs247_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs248_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs249_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs250_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs251_w15.dat
1_sampled_

1_sampled_data_obs_s3_m2/1_sampled_data_obs451_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs452_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs453_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs454_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs455_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs456_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs457_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs458_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs459_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs460_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs461_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs462_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs463_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs464_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs465_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs466_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs467_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs468_w15.dat
1_sampled_

1_sampled_data_obs_s3_m2/1_sampled_data_obs670_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs671_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs672_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs673_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs674_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs675_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs676_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs677_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs678_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs679_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs680_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs681_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs682_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs683_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs684_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs685_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs686_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs687_w15.dat
1_sampled_

1_sampled_data_obs_s3_m2/1_sampled_data_obs931_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs932_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs933_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs934_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs935_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs936_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs937_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs938_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs939_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs940_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs941_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs942_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs943_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs944_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs945_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs946_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs947_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs948_w15.dat
1_sampled_

1_sampled_data_obs_s3_m2/1_sampled_data_obs1168_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1169_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1170_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1171_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1172_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1173_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1174_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1175_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1176_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1177_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1178_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1179_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1180_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1181_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1182_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1183_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1184_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1185_

1_sampled_data_obs_s3_m2/1_sampled_data_obs1414_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1415_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1416_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1417_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1418_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1419_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1420_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1421_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1422_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1423_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1424_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1425_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1426_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1427_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1428_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1429_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1430_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1431_

1_sampled_data_obs_s3_m2/1_sampled_data_obs1643_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1644_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1645_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1646_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1647_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1648_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1649_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1650_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1651_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1652_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1653_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1654_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1655_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1656_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1657_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1658_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1659_w15.dat
1_sampled_data_obs_s3_m2/1_sampled_data_obs1660_